title:            MIND LOG
description:      Do Your Work. Don’t Be Stupid!
url: http://beatshon.com             # Site url.
signoff:   손병구      # Your name.
disqus_shortname: beatshon # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid: 267956736618918  # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         blog
    url:          http://beatshon.tumblr.com/
    external:     true
  - name:         Email
    url:          mailto:beatshon@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/beatshon/beatshon.github.com/commits/master
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart